version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Run Python Script
          command: |
            cd Desktop
            python python.py
